name: Redis Service Example

on:
  - push

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: python:3.8-alpine

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1

    - run: pip install -r requirements.txt
      working-directory: ./src

    - run: pytest tests
      working-directory: ./src
      env:
        REDIS_URL: redis://redis:${{ job.services.redis.ports[6379] }}/0

  vm-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1

    - run: pip install -r requirements.txt
      working-directory: ./src

    - run: pytest tests
      working-directory: ./src
      env:
        REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}/0
